// src/layout/RootLayout.tsx
import { MyContextProvider } from "@/components/home/MyContext"; // Import the provider
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context/AuthProvider";
import { LoadingProvider } from "@/components/utils/LoadingProvider";
import GoogleMapsScript from "@/components/utils/GoogleMapsScript";

// Load fonts with preload optimization
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "LES-PENEDES ENUGU",
  description: "Generated by create next app",
  metadataBase: new URL("http://localhost:3000"),
  openGraph: {
    title: "Les-Pendes Enugu",
    description: "Enugu Les-Pendes",
    url: "https://your-site.com",
    siteName: "Your Site",
    images: [
      {
        url: "/og-image.jpg",
        width: 800,
        height: 600,
        alt: "Og Image Alt Text",
      },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <head>
        {/* Additional metadata like Open Graph */}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the children with the context provider */}
        <AuthProvider>
          <LoadingProvider>
            <GoogleMapsScript />
            {children}
          </LoadingProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
